### ISSUE TITLE
Unable to set header while upload

### ISSUE THREAD

**Issue by jayprakashstar** [cloudnull/turbolift#99] opened 2015-08-06 09:45 UTC
@cloudnull 
Hi
I am using turbolift 2.3.1 and I tried this command while uploading
turbolift -u -a --os-rax-auth upload -s -OH Access-Control-Allow-Origin="http://example.com" -c

But I am getting error unrecognized command OH Access-Control-Allow-Origin="http://example.com"

But this works fine in turbolift 3.

But i guess turbolift is still unstable because upload is failing a lot so i m unable to use turbolift 3.
Is there any solution ?

Thanks

**Comment by cloudnull** [comment] 2015-08-16 06:04
I'm coding this issue because it's a duplicate of issue #97

**Closed by cloudnull** 2015-08-16 06:04 UTC
